name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.2
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  socket_io_client: ^3.1.4
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^21.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#1e1e2d"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    color: "#1e1e2d"
